-- Active: 1741734692764@@localhost@3306@lazzy_store
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-Sep-2025 2:50:55 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Producto` CASCADE
;

DROP TABLE IF EXISTS `producto_detalles` CASCADE
;

DROP TABLE IF EXISTS `venta_diaria` CASCADE
;

DROP TABLE IF EXISTS `venta_productodetalles` CASCADE
;

/* Create Tables */

CREATE TABLE `Producto`
(
	`id_prod` INT NOT NULL AUTO_INCREMENT,
	`nombre` varchar(250) NOT NULL,
	CONSTRAINT `PK_Producto` PRIMARY KEY (`id_prod` ASC)
)

;

CREATE TABLE `producto_detalles`
(
	`id_prod` INT NOT NULL,
	`fechaCompra_prod` DATETIME NOT NULL,
	`cantInicial_prod` INT NOT NULL COMMENT 'cantidad que compro',
	`cantActual_prod` INT NOT NULL COMMENT 'cantidad en existencia',
	`costo_prod` decimal(10,2) NOT NULL COMMENT 'lo que costo',
	`precioventa_prod` decimal(10,2) NULL COMMENT 'precio de venta',
	`pva_prod` decimal(10,2) NULL COMMENT 'precio promedio de venta',
	`ca_prod` decimal(10,2) NULL COMMENT 'costo promedio',
	CONSTRAINT `PK_producto_detalles` PRIMARY KEY (`id_prod` ASC, `fechaCompra_prod` ASC)
)

;

CREATE TABLE `venta_diaria`
(
	`id_venta` INT NOT NULL,
	`fecha_venta` DATETIME NOT NULL,
	`monto_venta` decimal(10,2) NULL,
	`tipo_pago_venta` INT NULL,
	CONSTRAINT `PK_venta_diaria` PRIMARY KEY (`id_venta` ASC, `fecha_venta` ASC)
)

;

CREATE TABLE `venta_productodetalles`
(
	`id_venta` INT NOT NULL,
	`id_prod` INT NOT NULL,
	`costo` decimal(10,2) NULL,
	`ventaprecio` decimal(10,2) NULL,
	`fecha_venta` DATETIME NOT NULL,
	CONSTRAINT `PK_venta_productodetalles` PRIMARY KEY (`id_venta` ASC, `id_prod` ASC, `fecha_venta` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `venta_productodetalles` 
 ADD INDEX `IXFK_venta_diaria_venta_productodetalles_02` (`id_venta` ASC, `fecha_venta` ASC, `id_prod` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `producto_detalles` 
 ADD CONSTRAINT `FK_Producto_producto_detalles`
	FOREIGN KEY (`id_prod`) REFERENCES `Producto` (`id_prod`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `venta_productodetalles` 
 ADD CONSTRAINT `FK_producto_detalles_venta_productodetalles`
	FOREIGN KEY (`id_prod`) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `venta_productodetalles` 
 ADD CONSTRAINT `FK_venta_diaria_venta_productodetalles`
	FOREIGN KEY (`id_venta`) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
