-- Active: 1758473912983@@localhost@3306@lazzy_store
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-Sep-2025 2:50:55 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Producto` CASCADE
;

DROP TABLE IF EXISTS `producto_detalles` CASCADE
;

DROP TABLE IF EXISTS `venta_diaria` CASCADE
;

DROP TABLE IF EXISTS `venta_productodetalles` CASCADE
;

/* Create Tables */

CREATE TABLE `Producto`
(
	`id_prod` INT NOT NULL AUTO_INCREMENT,
	`nombre_prod` varchar(250) NOT NULL,
	CONSTRAINT `PK_Producto` PRIMARY KEY (`id_prod` ASC)
)

;

CREATE TABLE `producto_detalles`
(
	`id_prod` INT NOT NULL,
	`fechaCompra_prod` DATETIME NOT NULL,
	`cantInicial_prod` INT NOT NULL COMMENT 'cantidad que compro',
	`cantActual_prod` INT NOT NULL COMMENT 'cantidad en existencia',
	`costo_prod` decimal(10,2) NOT NULL COMMENT 'lo que costo',
	`precioventa_prod` decimal(10,2) NULL COMMENT 'precio de venta',
	`pva_prod` decimal(10,2) NULL COMMENT 'precio promedio de venta',
	`ca_prod` decimal(10,2) NULL COMMENT 'costo promedio',
	`fechaVence_prod` DATE NULL,
	CONSTRAINT `PK_producto_detalles` PRIMARY KEY (`id_prod` ASC, `fechaCompra_prod` ASC)
)

;

CREATE VIEW view_prod AS
AS select `prod`.`nombre_prod` AS `nombre_prod`,`pdet`.`id_prod` AS `id_prod`,`pdet`.`fechaCompra_prod` AS `fechaCompra_prod`,`pdet`.`cantInicial_prod` AS `cantInicial_prod`,`pdet`.`cantActual_prod` AS `cantActual_prod`,`pdet`.`costo_prod` AS `costo_prod`,`pdet`.`precioventa_prod` AS `precioventa_prod`,`pdet`.`pva_prod` AS `pva_prod`,`pdet`.`ca_prod` AS `ca_prod`,if(`pdet`.`fechaVence_prod`=0,'no',pdet.fechaVence_prod) AS `fechaVence_prod` from (`lazzy_store`.`producto` `prod` left join `lazzy_store`.`producto_detalles` `pdet` on((`pdet`.`id_prod` = `prod`.`id_prod`)))

CREATE TABLE `venta_diaria`
(
	`id_venta` INT NOT NULL,
	`fecha_venta` DATETIME NOT NULL,
	`monto_venta` decimal(10,2) NULL,
	`tipo_pago_venta` INT NULL,
	CONSTRAINT `PK_venta_diaria` PRIMARY KEY (`id_venta` ASC, `fecha_venta` ASC)
)

;

CREATE TABLE `venta_productodetalles`
(
	`id_venta` INT NOT NULL,
	`id_prod` INT NOT NULL,
	`costo` decimal(10,2) NULL,
	`ventaprecio` decimal(10,2) NULL,
	`fecha_venta` DATETIME NOT NULL,
	CONSTRAINT `PK_venta_productodetalles` PRIMARY KEY (`id_venta` ASC, `id_prod` ASC, `fecha_venta` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `venta_productodetalles` 
 ADD INDEX `IXFK_venta_diaria_venta_productodetalles_02` (`id_venta` ASC, `fecha_venta` ASC, `id_prod` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `producto_detalles` 
 ADD CONSTRAINT `FK_Producto_producto_detalles`
	FOREIGN KEY (`id_prod`) REFERENCES `Producto` (`id_prod`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `venta_productodetalles` 
 ADD CONSTRAINT `FK_producto_detalles_venta_productodetalles`
	FOREIGN KEY (`id_prod`) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `venta_productodetalles` 
 ADD CONSTRAINT `FK_venta_diaria_venta_productodetalles`
	FOREIGN KEY (`id_venta`) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_prod` as 
SELECT producto_detalles.*,producto.nombre_prod FROM `producto_detalles` 
 RIGHT JOIN producto
 on producto.id_prod=producto_detalles.id_prod

SET FOREIGN_KEY_CHECKS=1 
;
